INSERT INTO `personals` (`id`, `codigo`, `nombre`, `turno`, `cargo`, `area`, `estado`, `hisopado`) VALUES
(1, 64687, 'CONDORI HINOJOSA WILFREDO', 'wilfredo', 'supervisor de produccion', 'produccion', 'Habilitado', 'No'),
(2, 67302, 'PACOSILLO CALSINA MIRIAM', 'wilfredo', 'analista htst', 'produccion', 'Habilitado', 'No'),
(3, 65257, 'CHURA COLQUE BENIGNO JOSE', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(4, 68587, 'ARUQUIPA COLLQUEHUANCA FAUSTO', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(5, 69273, 'MIRANDA VARGAS JULIO', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(6, 65641, 'JAVIER RAMOS VALENTIN', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(7, 66885, 'MAMANI FRANCO ERIK DEIBIT               ', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(8, 64222, 'RAMOS FUENTES JESUS BERNABE             ', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(9, 66679, 'JAVIER CHOQUE NORBERTO                  ', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(10, 65544, 'TITILE TITO ELVIS ELIO                  ', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(11, 65724, 'QUISPE PALLARICO JORGE LUIS', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(12, 68906, 'PAUCARA CALLISAYA VLADIMIR', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(13, 69538, 'RAMOS CRUZ GUSTAVO ENRIQUE', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(14, 65646, 'CHURA CHAMBI JOSE CARLOS ', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(15, 64662, 'ZABALETA QUISPE VICTOR  HUGO', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(16, 64453, 'QUISPE PERCA WILLAN', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(17, 68925, 'CONDORI HUARINO MAYCOL BRAYAN', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(18, 67016, 'MUCHIA TAHE ALEX', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(19, 62262, 'MOLLO CHOQUE MARLENE', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(20, 65129, 'MAMANI MAMANI NANCY', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(21, 62503, 'CASTRO URURI MERY', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(22, 65056, 'QUENTA LARUTA MIKAELA NIEVES            ', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(23, 64666, 'LIMACHI CONDORI MARICELA', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(24, 68646, 'CALSINA QUISPE HEBER SANTOS', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(25, 67720, 'QUISPE VELASCO CANDELARIA', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(26, 80109, 'VISCARRA MARCA CESAR', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(27, 65262, 'GUARACHI CHOQUE JULIA ', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(28, 68637, 'MAMANI CALLE ALVARO BLADIMIR', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(29, 68434, 'VILLARREAL CHAMBI DAVID NICOLAS', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(30, 80544, 'SULLCA CUARITE MARCELO JOSUE', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(31, 80262, 'HUANCA BAUTISTA LIMBERT KEVIN', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(32, 80369, 'AJORURO COCHI RENE CRISTIAN', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(33, 80545, 'GUTIERREZ CONDORI IVAN DOUGLAS', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(34, 80404, 'PATSI MAMANI JUAN DANIEL', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(35, 68449, 'MACHACA HUANCA  JUAN DE LA CRUZ', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(36, 80384, 'LAURA MOLINA CRISTHIAN', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(37, 80365, 'APAZA RONDO JUAN CARLOS', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(38, 66163, 'MAMANI QUISPE MARTHA ALEJANDRA', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(39, 66954, 'AQUINO MAMANI WILMER', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(40, 80308, 'MONTENEGRO MOLLINEDO GUSTAVO GERARDO', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(41, 69410, 'USNAYO CACERES ANGEL', 'wilfredo', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(42, 64089, 'CAMACHO RADA RAMIRO ALEJANDRO', 'camacho', 'supervisor de produccion', 'produccion', 'Habilitado', 'No'),
(43, 69315, 'HUAYHUA MABEL MILENKA', 'camacho', 'analista htst', 'produccion', 'Habilitado', 'No'),
(44, 62927, 'MAMANI VELA EDGAR', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(45, 62031, 'VARGAS CONDORI EDDY', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(46, 64858, 'QUISPE LAURA ALFREDO', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(47, 67438, 'QUISPE LAURA ANGEL', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(48, 62255, 'AJAHUANCA BENITO EVER                   ', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(49, 64430, 'TORREZ USNAYO RUBEN                     ', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(50, 64443, 'CALLE CATARI MARCO ANTONIO              ', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(51, 65472, 'MAMANI MARQUEZ REYNALDO                 ', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(52, 64686, 'CANAVIRI CANAVIRI ALAN', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(53, 65661, 'AJAHUANCA BENITO MARIO', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(54, 65137, 'MARCA CACHACA FLORENCIO', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(55, 66644, 'HUARANCA AJNO JUAN', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(56, 65499, 'GUTIERREZ COCHI LIMBERT ANTONIO', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(57, 67810, 'LIMA QUELCA DAVID', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(58, 62160, 'CALLISAYA TICONA HUGO ADHEMAR', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(59, 65272, 'COLLO ZEGARRA FAUSTINO JEMIO             ', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(60, 65491, 'QUISPE MAMANI RENE LAZARO', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(61, 66651, 'PATTY MAYTA MIRIAM PAULINA', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(62, 65106, 'VILLA RAMOS YANET', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(63, 65093, 'LAURA HUIZA SILVIA', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(64, 64006, 'MAMANI CARAZANI ROSALIA', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(65, 66669, 'QUISPE QUISPE NELLY', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(66, 69468, 'TORREZ TICACALA JOSE JOSE', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(67, 69118, 'QUISPE PAXI CRISTHIAN FERNANDO', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(68, 64261, 'VILLCA MAMANI ANDRES', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(69, 68955, 'SONCO FLORES MONICA MARLENE', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(70, 80131, 'RAMIREZ CALLISAYA RODRIGO', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(71, 69270, 'VELASCO VILLENA BENJAMIN', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(72, 69966, 'CALAMANI NINA JHON BRAYAN', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(73, 69514, 'SUXO QUISPE KEVIN', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(74, 80548, 'HERRERA MAMANI GUNNAR XAVIER', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(75, 80550, 'CLARES RAMOS JUAN ELVIS', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(76, 68895, 'TARQUI QUISPE YENSON YELMO', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(77, 69635, 'HUANCA FLORES CRISTHIAN EDUARDO', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(78, 69234, 'CANAVIRI CONDORI DAVID RUBEN', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(79, 80373, 'CONDORI TOLA RODRIGO', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(80, 66995, 'MAMANI CASTRO JHASMINA CELESTE', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(81, 68907, 'QUISPE PERCA JORGE LUIS ', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(82, 69815, 'HUMANA QUINTANA LUIS ', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(83, 80551, 'POMA CALLISAYA GIOVANNY FRANK', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(84, 69897, 'MAMANI CAVIÑA BRAYAN', 'camacho', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(85, 66948, 'VILA BARRA JUAN', 'juan', 'supervisor de produccion', 'produccion', 'Habilitado', 'No'),
(86, 80449, 'ARCE CUSSI BRIAN ERICK', 'juan', 'analista htst', 'produccion', 'Habilitado', 'No'),
(87, 62580, 'YANA CHURATA CARLOS', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(88, 62051, 'CALLE PAIRUMANI EFRAIN', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(89, 64446, 'CHURA TINTAYA MARCELO', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(90, 65060, 'CALLE OCHOA VILLANUEVA                  ', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(91, 66910, 'HUANCA POMA JUAN CARLOS', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(92, 64613, 'LIMARI BALTAZAR RAMIRO                  ', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(93, 64248, 'CHIPANA TANCARA FELIX NICOLAS           ', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(94, 64074, 'MERLO PALACIOS HEIDI BLANCA', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(95, 67817, 'CHOQUE RONDO ALFREDO', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(96, 66752, 'CHOQUE MAMANI JOSE', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(97, 64336, 'TOLA ALVAREZ GUSTABO', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(98, 66828, 'NINA COAQUIRA HENRY GONZALO', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(99, 69445, 'HUMANA QUINTANA MAX LUIS', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(100, 65068, 'SURCO HUANCA SUSANA LUCIA', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(101, 69604, 'QUECAÑA QUISPE NAIDA                    ', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(102, 64769, 'LAURA HUIZA LEONELA', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(103, 62653, 'BENITO BENITO MARITZA', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(104, 65115, 'MAMANI MURGA JUANA', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(105, 66184, 'GUTIERREZ FLORES RAQUEL', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(106, 69496, 'GOMEZ MAMANI JESUS', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(107, 69186, 'ALACAMA QUISPE CRISTHIAN DAVID', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(108, 65450, 'JAVIER RAMOS ANGELICA', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(109, 66617, 'LEANDRO TARQUI OMAR', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(110, 69924, 'SILVERA GUTIERREZ HUGO', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(111, 80222, 'MAMANI FABIAN YAMIL DERLIS', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(112, 80448, 'PACAJES TOLA ANAHI', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(113, 80393, 'MAMANI MITA JOEL', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(114, 80553, 'MAMANI CAVIÑA MIGUEL ANGEL', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(115, 80484, 'CASILLO ALANOCA IVAN JACINTO', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(116, 69681, 'GUTIERREZ MANCEDA MIGUEL ANGEL', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(117, 69914, 'RAMOS MERCADO RONAL DAVID', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(118, 69615, 'CHAIÑA COAQUIRA BEYMAR ANGEL', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(119, 80188, 'GUARACHI ASPI HENRY OMAR', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(120, 69912, 'QUISPE COCHI DIONES', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(121, 80292, 'MAMANI SUÑAGUA HENRY JESUS', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(122, 66796, 'TICONA MAMANI RODOLFO', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(123, 69799, 'VARGAS QUISPE ELIAN', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(124, 67546, 'CHOQUE RONDO MACARIO', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(125, 80057, 'ISRAEL GUZMAN SULLCATA ', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(126, 66937, 'LUIS EFRAIN PATTY MAYTA ', 'juan', 'ensachetador', 'produccion', 'Habilitado', 'No'),
(127, 66917, 'HUANCA QUITO JOSE LUIS                  ', 'uht', 'analista uht', 'uht', 'Habilitado', 'No'),
(128, 66080, 'AJNO CRUZ MARIA ANTONIA                 ', 'uht', 'analista uht', 'uht', 'Habilitado', 'No'),
(129, 64176, 'HUANCA QUISPE MIRIAM', 'uht', 'analista uht', 'uht', 'Habilitado', 'No'),
(130, 68515, 'QUISPE CONDORI EMMA', 'uht', 'analista uht', 'uht', 'Habilitado', 'No'),
(131, 65008, 'GUTIERREZ COCHI HERNANDO ROGER', 'central', 'ayudantes de insumos', 'insumos', 'Habilitado', 'No'),
(132, 69541, 'JIMENEZ MOLLO DIONICIO', 'central', 'ayudantes de insumos', 'insumos', 'Habilitado', 'No'),
(133, 64049, 'CONDORI MAMANI ELIANA ESTELA ', 'central', 'ayudantes de insumos', 'insumos', 'Habilitado', 'No'),
(134, 64617, 'HUANCA CRUZ IBER', 'central', 'ayudantes de insumos', 'insumos', 'Habilitado', 'No'),
(135, 68695, 'PACOSILLO CALSINA RONALD', 'central', 'ayudantes de insumos', 'insumos', 'Habilitado', 'No'),
(136, 68601, 'MAMANI CASTILLO REYNALDO', 'central', 'ayudantes de insumos', 'insumos', 'Habilitado', 'No'),
(137, 66936, 'QUISPE VIAMONTE OSCAR CESAR', 'central', 'ayudantes de insumos', 'insumos', 'Habilitado', 'No'),
(138, 66998, 'GOMEZ AJATA WILFREDO OVIDIO', 'central', 'ayudantes de laboratorio', 'ayudantes', 'Habilitado', 'No'),
(139, 66918, 'LLANOS CALANCHA JOSE ERNESTO', 'central', 'ayudantes de laboratorio', 'ayudantes', 'Habilitado', 'No'),
(140, 69331, 'ALCON MAMANI RONALDIÑHO', 'central', 'ayudantes de laboratorio', 'ayudantes', 'Habilitado', 'No'),
(141, 64428, 'SALINAS CHACOLLA VIRGINIA', 'central', 'ayudantes de laboratorio', 'ayudantes', 'Habilitado', 'No'),
(142, 67259, 'ALIAGA VILLCA SAULO JESUS', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(143, 67534, 'CASILLA CONDORI RUBEN ', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(144, 62605, 'MAMANI ACHOCALLA SARA', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(145, 62416, 'TANCARA MAMANI FELIX GUIDO              ', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(146, 69285, 'RODRIGUEZ SUCA JHENNY JHACIRA', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(147, 80071, 'LLANOS MAMANI MARIA ELENA', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(148, 80466, 'PAUCARA COQUENDO CAMILA', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(149, 80028, 'VILLA TRIGO CAMILO HASSAN', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(150, 66633, 'QUILLA CHOQUE JUAN CARLOS', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(151, 69047, 'ROJAS CALCINA GUSTAVO JUNIOR', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(152, 69318, 'LEDEZMA CALIZAYA ALEJANDRA', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(153, 68203, 'CALLISAYA MAMANI YHANET YHELKA', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(154, 66723, 'GONZALES HUANCA LIZETH', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(155, 67527, 'MAMANI CALLE VERONICA', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(156, 68853, 'MAMANI ESCALERA MIRIAM LIZETH', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(157, 67806, 'JARANDILLA  CALLE HELEN', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(158, 68855, 'CALLISAYA TERCEROS MABEL AMPARO', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(159, 69290, 'SANTALLA MANZANEDA JENNY', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(160, 69061, 'CONDORI NINACHOQUE HENRY BRUNO', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(161, 80026, 'CRUZ CARVAJAL ELISA', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(162, 69752, 'GOMEZ SARMIENTO MAURICIO', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(163, 69965, 'LOZA QUISPE JORGE RODRIGO', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(164, 80492, 'DIAZ CHOQUE ABEL ISAAC', 'central', 'administracion', 'administracion', 'Habilitado', 'No'),
(165, 62274, 'MAMANI LIMACHI JAIME', 'central', 'mantenimiento', 'administracion', 'Habilitado', 'No'),
(166, 66913, 'TORREZ ARRATIA MARCO ANTONIO', 'central', 'mantenimiento', 'administracion', 'Habilitado', 'No'),
(167, 69372, 'CONDE VELASQUEZ ABEL JORGE ', 'central', 'mantenimiento', 'administracion', 'Habilitado', 'No'),
(168, 80048, 'POMA QUISPE PERCY JUAN', 'central', 'mantenimiento', 'administracion', 'Habilitado', 'No'),
(169, 69297, 'MAMANI CHOQUEHUANCA OMAR', 'central', 'mantenimiento', 'administracion', 'Habilitado', 'No'),
(170, 80454, 'LIMA HIDALGO JIMMY FRANCO', 'central', 'mantenimiento', 'administracion', 'Habilitado', 'No'),
(171, 69623, 'MAMANI YUJRA ELMER', 'central', 'mantenimiento', 'administracion', 'Habilitado', 'No'),
(172, 80567, 'CHOQUE OSCO BRYAN ', 'central', 'mantenimiento', 'administracion', 'Habilitado', 'No'),
(173, 66927, 'CHOQUE MAMANI JESUS', 'central', 'mantenimiento', 'administracion', 'Habilitado', 'No'),
(174, 80566, 'CARLA FABIOLA VALDEZ', 'central', 'mantenimiento', 'administracion', 'Habilitado', 'No');
